export const CAMERA_MOVE_POS_YAW = 'CAMERA_MOVE_POS_YAW';
export const CAMERA_MOVE_NEG_YAW = 'CAMERA_MOVE_NEG_YAW';

export const CAMERA_MOVE_POS_PITCH = 'CAMERA_MOVE_POS_PITCH';
export const CAMERA_MOVE_NEG_PITCH = 'CAMERA_MOVE_NEG_PITCH';

export const CAMERA_MOVE_POS_X = 'CAMERA_MOVE_POS_X';
export const CAMERA_MOVE_NEG_X = 'CAMERA_MOVE_NEG_X';

export const CAMERA_MOVE_POS_Y = 'CAMERA_MOVE_POS_Y';
export const CAMERA_MOVE_NEG_Y = 'CAMERA_MOVE_NEG_Y';

export const CAMERA_MOVE_POS_Z = 'CAMERA_MOVE_POS_Z';
export const CAMERA_MOVE_NEG_Z = 'CAMERA_MOVE_NEG_Z';
